### ISSUE TITLE
How to translate into Chinese

### ISSUE THREAD

**Issue by jiangyi0923** [Artenuvielle/GW2-SCT#1]
How to translate into Chinese

**Comment by Artenuvielle** [comment]
I've put together a list of strings in an ini file. But be aware that there are over 600 lines to translate (some of them repeat, so feel free to use a find/replace all feature).
[lang_en.zip](https://github.com/Artenuvielle/GW2-SCT/files/2541949/lang_en.zip)

If you have any questiones where any of the strings are used, feel free ask me.

**Comment by jiangyi0923** [comment]
In the Chinese version, your plugin cannot display Chinese characters. like "(???)"  this

**Comment by Artenuvielle** [comment]
The language file is not read by the current version but I'm working on it. Sadly I cannot test this on the cinese client but I'll do my best.

**Comment by Artenuvielle** [comment]
Check out this development snapshot:
[d3d9_arcdps_sct.zip](https://github.com/Artenuvielle/GW2-SCT/files/2544241/d3d9_arcdps_sct.zip)
Place your language file in /addons/sct/lang.ini
Also note that I was missing one entry in the section [Option_UI]:
General_Enabled = SCT enabled

**Comment by jiangyi0923** [comment]
![qq 20181103094732](https://user-images.githubusercontent.com/40364405/47947712-866bd800-df5c-11e8-9c57-4d427b813da9.png)
![qq 20181103100206](https://user-images.githubusercontent.com/40364405/47947713-87046e80-df5c-11e8-925a-9ae4003c7fd8.png)
![qq 20181103101836](https://user-images.githubusercontent.com/40364405/47947714-87046e80-df5c-11e8-8e06-0b9abf394dc5.png)
1.  /n invalid
2. [X Hits] no translation
3. incoming events and outgoing events  no translation
4. The font causes the interface to be too large, please use 12.0f-15.0f size, or increase the settings in the options or configuration file settings.

**Comment by Artenuvielle** [comment]
Addressing those issues:
1. Reading data from ini file ecaped \n as \\n. Fixed this.
2. Added missing translation. (Also the string "Multiple_Sources")
3. Those names are saved in sct.ini and therefore can't really be translated. They are only read once when there is no sct.ini file. However, I added under [General] these lines:
    Default_Scroll_Area_Incoming = Incoming Events
    Default_Scroll_Area_Outgoing = Outgoing Events
4. SCT Options now tries to use /addons/arcdps/arcdps_font.ttf if it exist. I accidently used font size 22 for this. I fixed this to read the font size from /addons/arcdps/arcdps.ini ([display_altui] section, font_size key) and fall back to 12.

Try this:
[d3d9_arcdps_sct.zip](https://github.com/Artenuvielle/GW2-SCT/files/2544816/d3d9_arcdps_sct.zip)

**Comment by jiangyi0923** [comment]
Thank you for your help, and finally there is a question, why getting "Shielded" will show up as "Heal over time"

**Comment by jiangyi0923** [comment]
Why right and left  both  show "Heal over time"?
 if you can change to 
the left to show the treatment given by other players, 
the right side shows player treatment,
I mean to show myself  treatment of my own treatment ,to the right without repeating it to the left.

**Comment by Artenuvielle** [comment]
You are right: shield messages are bugged and I'm working on it (and so are invulnerable message).

As for your suggestion: if you apply anything onto yourself (heal, hot, condi with necro, ...) it is theoretically both: incoming to your character and outgoing from your character. In the options are two ways to prevent this. Both are in the "General" tab - "Show self messages only as incoming" and "Show outgoing messages only for target" - with the latter also removing all outgoing messages which are not applied to current ingame target.

**Comment by Artenuvielle** [comment]
Here is a new build:
[d3d9_arcdps_sct.zip](https://github.com/Artenuvielle/GW2-SCT/files/2545066/d3d9_arcdps_sct.zip)
 There are 4 new message types and the englich default for some have changed, here is a list:
`[messagePlayerOutgoingShieldGot]
title = Shield Received
Parameter_Description_v = Amount of Shield
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = +%v %i

[messagePlayerOutgoingShield]
title = Shielded Damage
Parameter_Description_v = Amount of damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = %v -=absorb=- %i

[messagePlayerIncomingShieldGot]
title = Shielded
Parameter_Description_v = Amount of damage
Parameter_Description_n = Name of the shield source
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i +%v

[messagePlayerIncomingShield]
title = Shield damage
Parameter_Description_v = Amount of damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i %v -=absorb=-

[messagePetOutgoingShieldGot]
title = Shielded
Parameter_Description_v = Amount of shield
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone shielding
Parameter_Description_i = Skillicon
Default_Value = +%v %i

[messagePetOutgoingShield]
title = Shield damage
Parameter_Description_v = Amount of damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = %v -=absorb=- %i

[messagePetIncomingShieldGot]
title = Shielded
Parameter_Description_v = Amount of shield
Parameter_Description_n = Name of the shield source
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet +%v

[messagePetIncomingShield]
title = Shield damage
Parameter_Description_v = Amount of damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet %v -=absorb=-`

**Comment by jiangyi0923** [comment]
Fixed! But fps is falling too fast. 60fps drops to 18fps or even lower during combat. This is a big problem.

**Comment by Artenuvielle** [comment]
Ooops, looks like you got a build with debug symbols enabled which slows down the game horribly. I usually use these for debugging event data. Here you go:
[d3d9_arcdps_sct.zip](https://github.com/Artenuvielle/GW2-SCT/files/2545666/d3d9_arcdps_sct.zip)

**Comment by jiangyi0923** [comment]
ok  all
