### ISSUE TITLE
New version not loading

### ISSUE THREAD

**Issue by neopoison18** [Artenuvielle/GW2-SCT#10]
As title says, the new version isn't loading or showing at arcdps, both are updated. The older versions works normally and creates the sct folder, but still have the damage/heal bug, meanwhile the new version doesn't seem to load at all ingame and isn't creating the sct folder.

**Comment by Artenuvielle** [comment]
Could you please provide information about the system you are running under.

I had to change my development setup and following this I changed to a new compiler version. Maybe this arises the issue?

**Comment by DunkingDuck** [comment]
> 
> 
> As title says, the new version isn't loading or showing at arcdps, both are updated. The older versions works normally and creates the sct folder, but still have the damage/heal bug, meanwhile the new version doesn't seem to load at all ingame and isn't creating the sct folder.

got the same problem, old version is working fine apart from the healing/damage bug, new one won't seem to load. I'm still using Windows 7 with GW2 running on my SSD not sure if the old operating system is a problem in this. I tried running the old .dll file but i updated the old .config file with the code from the new version... just ended up crashing my game once I attacked an enemy lul (atleast I tried)

**Comment by neopoison18** [comment]
I'm on Windows 10 Pro, Version 1809.

**Comment by Nayarunicorn** [comment]
Hiya, Never used this before but did follow instructions to the letter so in theory it should be working. Nothing is happening in game, arcdps is running fine on 25th March patch though. Gw2hook still working fine too.

Windows 10 Pro, Version 1909
OS Build 18363.720

Any other info that might be helpful? ^_^

Thanks for creating this! Even if I don't get to use it in the end x)

**Comment by Artenuvielle** [comment]
could you please provide the log file of arcdps located at 'GW2 dir\addons\arcdps\arcdps.log'?

**Comment by Nayarunicorn** [comment]
Mar 27 03:16:57 arcdps 20200325.120355-323-x64
Mar 27 03:16:57 client: gw2 0x7FF645680000-0x7FF647B04000 (0xA2B6C1A1)
Mar 27 03:16:57 client: arcdps 0x7FFE93510000-0x7FFE935EC000 (0x4D928E3D)
Mar 27 03:16:57 client: chainloading d3d9
Mar 27 03:16:59 config: loading from "D:\Guild Wars 2\addons\arcdps\arcdps.ini"

That's all that's in there for today =)

**Comment by Artenuvielle** [comment]
I guess you made sure that SCT is located in the bin64 directory and still called 'd3d9_arcdps_sct.dll'?

**Comment by Nayarunicorn** [comment]
Indeed,

Filepath is: D:\Guild Wars 2\bin64
Filename is: d3d9_arcdps_sct.dll

C Drive is much too small to do anything with for some reason so all my installs go in my D drive. Not sure if that'll make a difference to this.

Anything you'd like me to edit or fiddle with, do let me know.

**Comment by Artenuvielle** [comment]
No, having it on drive D: is fine. I have mine in D:\Games\Guild Wars 2\bin64 aswell.
Do other arcdps addons like the mechanic addon or old SCT versions load correctly? You can always check which addons loaded in the arcdps.ini file. There should be a line like:
`Mar 27 13:47:38 extensions: GW2 SCT 0x7FFB4E9F0000-0x7FFB4EAEA000 (1.2, 0x8E877AA2)`

**Comment by Artenuvielle** [comment]
Also your arcdps log says you are chainloading another d3d9.dll have you tried disabling this?

**Comment by Nayarunicorn** [comment]
1) I removed sct version 1.2 and put in version 1.1
2) Logged in and floating damage numbers are there
3) Found "Mar 27 13:25:21 extensions: GW2 SCT 0x7FFF9C410000-0x7FFF9C515000 (1.1d, 0xD5A3B4AC)" in arcdps.log rather than .ini
4) An "SCT" folder has been created in gw2/addons where there was not one before

I will remove the other d3d9.dll (gw2hook) and re-add sct 1.2 and report back shortly

**Comment by Nayarunicorn** [comment]
I completed the above (Added 1.2 RC1 and removed gw2hook) - no sct showing in game or in the arcdps.log
> Mar 27 14:21:35 arcdps 20200325.120355-323-x64
> Mar 27 14:21:36 client: gw2 0x7FF7C6900000-0x7FF7C8D84000 (0xA2B6C1A1)
> Mar 27 14:21:36 client: arcdps 0x7FFF9EAE0000-0x7FFF9EBBC000 (0x4D928E3D)
> Mar 27 14:21:36 client: chainloading d3d9
> Mar 27 14:21:37 config: loading from "D:\Guild Wars 2\addons\arcdps\arcdps.ini"
> 

For reference I then added 1.1 RC3 again without adding gw2hook, it works and the .log file reads as: 
> Mar 27 14:26:04 arcdps 20200325.120355-323-x64
> Mar 27 14:26:05 client: gw2 0x7FF7C6900000-0x7FF7C8D84000 (0xA2B6C1A1)
> Mar 27 14:26:05 client: arcdps 0x7FFF9D980000-0x7FFF9DA5C000 (0x4D928E3D)
> Mar 27 14:26:05 client: chainloading d3d9
> Mar 27 14:26:06 extensions: GW2 SCT 0x7FFF9C1F0000-0x7FFF9C2F5000 (1.1d, 0xD5A3B4AC)
> Mar 27 14:26:06 config: loading from "D:\Guild Wars 2\addons\arcdps\arcdps.ini"

I'll try removing everything in bin64 except for sct and arcdps, including the chainloader dll which I'm assuming would only be chainloading sct in this case as gw2hook is removed. - And oops I didn't remove gw2hook from /addons so I'll do that too for good measure. Right now the only thing in /addons is arcdps and in /bin64 is d3d9 for arc and then the sct one too... here goes..

Aaaand nothing:
> Mar 27 14:32:52 arcdps 20200325.120355-323-x64
> Mar 27 14:32:52 client: gw2 0x7FF7C6900000-0x7FF7C8D84000 (0xA2B6C1A1)
> Mar 27 14:32:52 client: arcdps 0x7FFF9D980000-0x7FFF9DA5C000 (0x4D928E3D)
> Mar 27 14:32:54 config: loading from "D:\Guild Wars 2\addons\arcdps\arcdps.ini"

I'll re-add everything back in again for now.

**Comment by Artenuvielle** [comment]
I have no idea why this is happening. It might still be a compiler issue. However I contacted deltaconnected about this issue.

**Comment by Artenuvielle** [comment]
Could you try the version included in this zip archive and see if it resolves the issue?
[d3d9_arcdps_sct.zip](https://github.com/Artenuvielle/GW2-SCT/files/4394910/d3d9_arcdps_sct.zip)

**Comment by DunkingDuck** [comment]
tried the new one, still nothing, only using arcdps and the sctl, no other add on 

Mar 27 18:12:28 arcdps 20200325.120355-323-x64
Mar 27 18:12:28 client: gw2 0x13FDC0000-0x142244000 (0xA2B6C1A1)
Mar 27 18:12:28 client: arcdps 0x7FED5020000-0x7FED50FC000 (0x4D928E3D)
Mar 27 18:12:29 config: loading from "C:\Program Files\Guild Wars 2\addons\arcdps\arcdps.ini"

**Comment by Nayarunicorn** [comment]
Same here, no luck on the zip archive for me. Also tried the original 1.2 rc1 on my retired laptop but same issue. System info for what it's worth:

> Windows 10 Pro 1903
> Build 18362.657

Cheers! =)

**Comment by Artenuvielle** [comment]
deltaconnected made me aware that you may be missing the correct Microsoft Visual C++ redistributable. Maybe check if this helps: https://support.microsoft.com/de-de/help/2977003/the-latest-supported-visual-c-downloads#section-2

**Comment by Nayarunicorn** [comment]
That was it. I installed https://aka.ms/vs/16/release/vc_redist.x64.exe and SCT version 1.2 RC1 is working. Nice one! =)

**Comment by neopoison18** [comment]
Thank you very much, it solved for me too. Happy that I can use it again, tyvm Artenuvielle
