### ISSUE TITLE
Not being able to turn off some floaters (missing language key)

### ISSUE THREAD

**Issue by DunkingDuck** [Artenuvielle/GW2-SCT#12]
I'm not able to turn off some of the floaters like "Invulnerable!" on Outgoing for example, because of "missing language key", didn't really bother me at first but with the newest arc update today its giving me floaters for regenerating endurance or when gaining luck lol, which makes the UI kinda cluttered.

**Comment by Artenuvielle** [comment]
The combat API from arcdps from yesterdays build is a bit broken. I already got in touch with deltaconnected.
Can you tell me though where exactly you see the "missing language key" message and maybe provide your sct.ini, sct.log and lang.ini?

**Comment by DunkingDuck** [comment]
The missing language key appears on the "messages" tab on each floater option you are able to turn on/off, like showing healing on outgoing or dmg on incoming, which results in me not being able to turn them off and all of them being enabled 24/7. got nothing on the sct.log but heres the lang.ini: 

[General]
Outdated_Popup_Title = ArcDPS outdated
Outdated_Popup_Content = You are running an old version of ArcDPS some features of SCT
Outdated_Popup_Found_Version = Found version
Outdated_Popup_Required_Version = Required version
Outdated_Popup_Confirmation = OK
Font = Font
Font_Size = Font Size
Font_Master = Master Font
Font_Default = Default Font
Text_Align_Left = Left
Text_Align_Center = Mitte
Text_Align_Right = Right
Text_Curve_Left = Left
Text_Curve_Straight = Straight
Text_Curve_Right = Right
Old_Save_Popup_Title = Old Save File Version
Old_Save_Popup_Content = The found options file was saved with an older version of GW2 SCT.
Old_Save_Popup_Backup_Made = A backup of your old options save file can be found at:
Old_Save_Popup_Confirmation = OK
Unknown_Skill_Source = <Area>
Unknown_Skill_Target = <Area>
Unknown_Skill_Name = <Skill>
Default_Scroll_Area_Incoming = Incoming Events
Default_Scroll_Area_Outgoing = Outgoing Events


[Option_UI]
Title = SCT Options
Menu_Bar_General = General
Menu_Bar_Scroll_Areas = Scroll Areas
Menu_Bar_Messages = Messages
Menu_Bar_Profession_Colors = Profession Colors
Menu_Bar_Filtered_Skill_IDs = Filtered Skill IDs
Menu_Bar_Skill_Icons = Skill Icons
General_Enabled = SCT enabled
General_Scrolling_Speed = Scrolling Speed
General_Drop_Shadow = Drop Shadow
General_Max_Messages = Maximal Messages in Stack
General_Combine_Messages = Combine all Messages
General_Self_Only_As_Incoming = Show self messages only as incoming
General_Out_Only_For_Target = Show outgoing messages only for target
Scroll_Areas_None_Exist = None
Scroll_Areas_New = New Scroll Area
Messages_Category = Message Category
Messages_Category_Player_Out = Player Outgoing
Messages_Category_Player_In = Player Incoming
Messages_Category_Pet_Out = Pet Outgoing
Messages_Category_Pet_In = Pet Incoming
Profession_Colors_Guardian = Guardian
Profession_Colors_Warrior = Warrior
Profession_Colors_Engineer = Engineer
Profession_Colors_Ranger = Ranger
Profession_Colors_Thief = Thief
Profession_Colors_Elementalist = Elementalist
Profession_Colors_Mesmer = Mesmer
Profession_Colors_Necromancer = Necromancer
Profession_Colors_Revenant = Revenant
Profession_Colors_Undetectable = Undetectable profession
Skill_Icons_Warning = Warning: Using skill icons will establish an additional connection to the GW2 rendering API. All downloaded icons will be saved in
Skill_Icons_Enable = Enable skill icons
Skill_Icons_Preload_Description = Preloading skill icons will download every possible skill icon from the GW2 rendering API. This will require ~25MB of free memory space available. If not enabled, icons will be only downloaded as needed.
Skill_Icons_Preload = Preload all skill icons


[Message]
Multiple_Sources = Multiple
Number_Of_Hits = Hits


[Scroll_Area_Option_UI]
Horizontal_Offset = Horizontal Offset
Vertical_Offset = Vertical Offset
Width = Width
Height = Height
Text_Align = Text Align
Text_Flow = Text Flow
Delete_Confirmation_Title = Delete?
Delete_Confirmation_Content = Are you sure you want to delete this scroll area?
Delete_Confirmation_Confirmation = OK
Delete_Confirmation_Cancel = Cancel


[Message_Option_UI]
Output_Scroll_Area = Output Scroll Area
Template = Template
Available_Parameters = Available template parameters


[Skill_Filter_Option_UI]
Delete_Confirmation_Title = Delete?
Delete_Confirmation_Content = Are you sure you want to delete this skill id filter?
Delete_Confirmation_Confirmation = OK
Delete_Confirmation_Cancel = Cancel


[messagePlayerOutgoingPhysical]
Parameter_Description_v = Amount of damage
title = Physical Hit
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePlayerOutgoingCrit]
Parameter_Description_v = Amount of damage
title = Physical Crit
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePlayerOutgoingBleeding]
Parameter_Description_v = Amount of damage
title = Bleeding Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePlayerOutgoingBurning]
Parameter_Description_v = Amount of damage
title = Burning Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePlayerOutgoingPoison]
Parameter_Description_v = Amount of damage
title = Poison Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePlayerOutgoingConfusion]
Parameter_Description_v = Amount of damage
title = Confusion Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePlayerOutgoingRetaliation]
Parameter_Description_v = Amount of damage
title = Retaliation Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePlayerOutgoingTorment]
Parameter_Description_v = Amount of damage
title = Torment Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePlayerOutgoingDoT]
Parameter_Description_v = Amount of damage
title = Other Continuous Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePlayerOutgoingHeal]
Parameter_Description_v = Amount of heal
title = Heal
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = +%v %i


[messagePlayerOutgoingHoT]
Parameter_Description_v = Amount of heal
title = Heal over Time
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = +%v %i


[messagePlayerOutgoingShieldGot]
Parameter_Description_v = Amount of Shield
title = Shield Received
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = +%v %i


[messagePlayerOutgoingShield]
Parameter_Description_v = Amount of damage
title = Shielded Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = %v -=absorb=- %i


[messagePlayerOutgoingBlock]
title = Block
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = Block! %i


[messagePlayerOutgoingEvade]
title = Evade
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = Evade! %i


[messagePlayerOutgoingInvulnerable]
title = Invulnerable
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = Invulnerable! %i


[messagePlayerOutgoingMiss]
title = Miss
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_i = Skillicon
Default_Value = Miss! %i


[messagePlayerIncomingPhysical]
Parameter_Description_v = Amount of damage
title = Physical Hit
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i ([col=%c]%n[/col]) -[col=FFFFFF]%v[/col]


[messagePlayerIncomingCrit]
Parameter_Description_v = Amount of damage
title = Physical Crit
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i ([col=%c]%n[/col]) -[col=FFFFFF]%v[/col]


[messagePlayerIncomingBleeding]
Parameter_Description_v = Amount of damage
title = Bleeding Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i ([col=%c]%n[/col]) -[col=E84B30]%v[/col]


[messagePlayerIncomingBurning]
Parameter_Description_v = Amount of damage
title = Burning Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i ([col=%c]%n[/col]) -[col=FF9E32]%v[/col]


[messagePlayerIncomingPoison]
Parameter_Description_v = Amount of damage
title = Poison Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i ([col=%c]%n[/col]) -[col=00C400]%v[/col]


[messagePlayerIncomingConfusion]
Parameter_Description_v = Amount of damage
title = Confusion Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i ([col=%c]%n[/col]) -[col=B243FF]%v[/col]


[messagePlayerIncomingRetaliation]
Parameter_Description_v = Amount of damage
title = Retaliation Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i ([col=%c]%n[/col]) -[col=FFED00]%v[/col]


[messagePlayerIncomingTorment]
Parameter_Description_v = Amount of damage
title = Torment Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i ([col=%c]%n[/col]) -[col=24451F]%v[/col]


[messagePlayerIncomingDoT]
Parameter_Description_v = Amount of damage
title = Other Continuous Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i ([col=%c]%n[/col]) -[col=45CDFF]%v[/col]


[messagePlayerIncomingHeal]
Parameter_Description_v = Amount of heal
title = Heal
Parameter_Description_n = Name of the healing source
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i +%v


[messagePlayerIncomingHoT]
Parameter_Description_v = Amount of heal
title = Heal over Time
Parameter_Description_n = Name of the healing source
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i +%v


[messagePlayerIncomingShieldGot]
Parameter_Description_v = Amount of damage
title = Shielded
Parameter_Description_n = Name of the shield source
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i +%v


[messagePlayerIncomingShield]
Parameter_Description_v = Amount of damage
title = Shield damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i %v -=absorb=-


[messagePlayerIncomingBlock]
title = Block
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Block!


[messagePlayerIncomingEvade]
title = Evade
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Evade!


[messagePlayerIncomingInvulnerable]
title = Invulnerable
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Invulnerable!


[messagePlayerIncomingMiss]
title = Miss
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Miss!


[messagePetOutgoingPhysical]
Parameter_Description_v = Amount of damage
title = Physical Hit
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePetOutgoingCrit]
Parameter_Description_v = Amount of damage
title = Physical Crit
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePetOutgoingBleeding]
Parameter_Description_v = Amount of damage
title = Bleeding Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePetOutgoingBurning]
Parameter_Description_v = Amount of damage
title = Burning Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePetOutgoingPoison]
Parameter_Description_v = Amount of damage
title = Poison Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePetOutgoingConfusion]
Parameter_Description_v = Amount of damage
title = Confusion Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePetOutgoingRetaliation]
Parameter_Description_v = Amount of damage
title = Retaliation Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePetOutgoingTorment]
Parameter_Description_v = Amount of damage
title = Torment Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePetOutgoingDoT]
Parameter_Description_v = Amount of damage
title = Other Continuous Damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = %v %i


[messagePetOutgoingHeal]
Parameter_Description_v = Amount of heal
title = Heal
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone healing
Parameter_Description_i = Skillicon
Default_Value = +%v %i


[messagePetOutgoingHoT]
Parameter_Description_v = Amount of heal
title = Heal over Time
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone healing
Parameter_Description_i = Skillicon
Default_Value = +%v %i


[messagePetOutgoingShieldGot]
Parameter_Description_v = Amount of shield
title = Shielded
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone shielding
Parameter_Description_i = Skillicon
Default_Value = +%v %i


[messagePetOutgoingShield]
Parameter_Description_v = Amount of damage
title = Shield damage
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = %v -=absorb=- %i


[messagePetOutgoingBlock]
title = Block
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = Block! %i


[messagePetOutgoingEvade]
title = Evade
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = Evade! %i


[messagePetOutgoingInvulnerable]
title = Invulnerable
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = Invulnerable! %i


[messagePetOutgoingMiss]
title = Miss
Parameter_Description_n = Name of the skills target
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_i = Skillicon
Default_Value = Miss! %i


[messagePetIncomingPhysical]
Parameter_Description_v = Amount of damage
title = Physical Hit
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet -%v


[messagePetIncomingCrit]
Parameter_Description_v = Amount of damage
title = Physical Crit
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet -%v


[messagePetIncomingBleeding]
Parameter_Description_v = Amount of damage
title = Bleeding Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet -%v


[messagePetIncomingBurning]
Parameter_Description_v = Amount of damage
title = Burning Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet -%v


[messagePetIncomingPoison]
Parameter_Description_v = Amount of damage
title = Poison Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet -%v


[messagePetIncomingConfusion]
Parameter_Description_v = Amount of damage
title = Confusion Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet -%v


[messagePetIncomingRetaliation]
Parameter_Description_v = Amount of damage
title = Retaliation Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet -%v


[messagePetIncomingTorment]
Parameter_Description_v = Amount of damage
title = Torment Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet -%v


[messagePetIncomingDoT]
Parameter_Description_v = Amount of damage
title = Other Continuous Damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet -%v


[messagePetIncomingHeal]
Parameter_Description_v = Amount of healing
title = Heal
Parameter_Description_n = Name of the healing source
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone healing
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet +%v


[messagePetIncomingHoT]
Parameter_Description_v = Amount of healing
title = Heal over Time
Parameter_Description_n = Name of the healing source
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone healing
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet +%v


[messagePetIncomingShieldGot]
Parameter_Description_v = Amount of shield
title = Shielded
Parameter_Description_n = Name of the shield source
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet +%v


[messagePetIncomingShield]
Parameter_Description_v = Amount of damage
title = Shield damage
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet %v -=absorb=-


[messagePetIncomingBlock]
title = Block
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet Block!


[messagePetIncomingEvade]
title = Evade
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet Evade!


[messagePetIncomingInvulnerable]
title = Invulnerable
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet Invulnerable!


[messagePetIncomingMiss]
title = Miss
Parameter_Description_n = Name of the attacker
Parameter_Description_s = Skillname
Parameter_Description_p = Name of the pet/clone attacking
Parameter_Description_c = Color for the skills source profession (use: [col=%c]...[/col])
Parameter_Description_i = Skillicon
Default_Value = %i Pet Miss!

**Comment by DunkingDuck** [comment]
[lang.txt](https://github.com/Artenuvielle/GW2-SCT/files/4414425/lang.txt)

**Comment by Artenuvielle** [comment]
In your sct config it says you are still on 1.2a (which is 1.2-RC2 in Releases page). Are you sure you have the newest version of GW2 SCT?

Also I would suggest you deleting the lang.ini file (since there are some corrupted strings in there). It will be recreated once GW2 starts up again.

**Comment by DunkingDuck** [comment]
hmm interesting, thought i was using the newest version, will check that out

**Comment by DunkingDuck** [comment]
alright so getting the newest version again and deleting the lang.ini worked out, no "missing language key" any more and I'm able to turn of the floaters individually, endurance regen is still being shown as healing tho lul, but as you said thats a different issue, thanks a lot for the help!
