### ISSUE TITLE
Number of font files

### ISSUE THREAD

**Issue by wolfrik17** [Artenuvielle/GW2-SCT#14]
Adding too many font files in the font folder causes the game to crash

**Comment by Artenuvielle** [comment]
Can you give me a rough number of how many font files are needed to reproduce this issue? Also what are your system specs hardwarewise (espacially RAM)?

**Comment by wolfrik17** [comment]
I can't remember exactly how many it was and I can't test it right now but I think I just downloaded the entire Roboto font family which has 12 fonts + I had like 3-4 other fonts. Removing the fonts solved the issue. I have 16GB of RAM.

**Comment by Artenuvielle** [comment]
I will have a look into it soon.

**Comment by wolfrik17** [comment]
I can't replicate the issue anymore, maybe the problem was with one of the fonts I used and not the number of files since the game started to crash after I copied a bunch of fonts at once. Feel free to close the issue.
