### ISSUE TITLE
When entering Window mode with Alt+Enter game freezes

### ISSUE THREAD

**Issue by jhfyang** [Artenuvielle/GW2-SCT#15]
If you do Alt+Enter too quickly game freezes like this

![image](https://user-images.githubusercontent.com/25792174/89098657-c8ec6e00-d3e9-11ea-916a-5af08eeb2264.png)

**Comment by Artenuvielle** [comment]
Confirmed, game freezes indefinately sometimes when alt+enter with sct enabled.

**Comment by Artenuvielle** [comment]
Will be fixed in the next release (2.0-RC2).
