### ISSUE TITLE
Terrible font scaling

### ISSUE THREAD

**Issue by Mourdraug** [Artenuvielle/GW2-SCT#20]
Fonts scale pretty terribly, anything larger than 30 becomes pixelated.

![Gw2-64_HVYUxI8DQ1](https://user-images.githubusercontent.com/858692/104078232-4f20a200-521d-11eb-89b4-fa76851f2129.png)

**Comment by Artenuvielle** [comment]
Can you please tell me what font file you we're using, so I can reproduce this?

**Comment by Artenuvielle** [comment]
Nevermind, I was able to reproduce this during testing. Will have a deeper look into it.

**Comment by Artenuvielle** [comment]
This is fixed as of pre-release 2.0-RC1.
