### ISSUE TITLE
SCT not working after newest ARC DPS Update?

### ISSUE THREAD

**Issue by Neutraz** [Artenuvielle/GW2-SCT#22]
Hi,

since today's ARC DPS update it seems like SCT isn't working anymore.

Any chance for an update? Would be really awesome.

Changelog ARC DPS - https://www.deltaconnected.com/arcdps/ : 

 feb.23.2021: updated for feb23 game build maybe.
 feb.23.2021: fixed area stats toggle via hotkey when options open.
 feb.23.2021: changed to process all hotkeys with one keypress (eg bind multiple area stats).
 feb.23.2021: added detection for buff effect buff conditions to sim.
 feb.23.2021: out-of-date addons will fail to load with the imgui version mismatch error.
 feb.23.2021: window positions will be reset.
 feb.23.2021: imgui appearance options will be reset.
 feb.23.2021: evtc/api: updated imgui to 1.80. see changes to arcdps_exports and get_init_addr in example cpp.
 feb.23.2021: evtc/api: treat buff remove events where the buffs origin was a squad member as squad event.
 feb.23.2021: evtc/api: added buff conditions to cbts buffformula (float[2] from src_instid, see readme).

Thanks and regards,
Neutra

**Comment by hk3wx** [comment]
I had to remove the DLL in order to start the game ¬¬

**Comment by Artenuvielle** [comment]
I will address this issue very shortly.

**Comment by Artenuvielle** [comment]
solved with [release candidate 1.3-RC2](https://github.com/Artenuvielle/GW2-SCT/releases/tag/1.3-RC2)
