### ISSUE TITLE
Scrolling text is slightly blurry in 1440p

### ISSUE THREAD

**Issue by Ririshi** [Artenuvielle/GW2-SCT#25]
I just wanted to let you know that it feels like the scrolling text is a little blurry when I'm playing in 1440p. I tried to change some settings around but I couldn't find a way to fix it. I am running d912pxy + reshade as well, if that matters. My rig is a 1440p 165Hz screen powered by a RTX 2070 Super and a Ryzen 3900X. Not sure what further info I can provide, but I'd be happy to help in debugging the issue! I will attach an image later if necessary.

**Comment by Artenuvielle** [comment]
On which version are you experiencing this issue? Are you on the prerelease for 2.0? If not, try that one. Otherwise it would help if you could specify the font and font size you're using.

**Comment by Ririshi** [comment]
Well, I managed to forget the most basic info. I am using the 1.3 RC4 version with the font settings on default (e.g. default font, 22 for normal hits and 30 for crits).

I could try 2.0 tonight, but I'll need to read the manual installation first, since I used the mod manager to install SCT.

**Comment by Artenuvielle** [comment]
This will be probably the same issue as in https://github.com/Artenuvielle/GW2-SCT/issues/20.
This should be fixed by the prerelease for 2.0 since the font rendering was completely changed.

**Comment by Ririshi** [comment]
Thanks, will try that out! Got a little screenshot for ya, too (only 22 size so not very obvious). Will probably not be relevant, though, since you said it's fixed in 2.0.
![image](https://user-images.githubusercontent.com/8461226/111193852-ea861880-85ba-11eb-882a-5810ef5e34de.png)
