### ISSUE TITLE
can't load sct\fonts\arcdps_font.ttf

### ISSUE THREAD

**Issue by jiangyi0923** [Artenuvielle/GW2-SCT#27]
GW2 SCT: loading: C:\jz2\addons\sct\fonts\arcdps_font.ttf
GW2 SCT: Failed initializing font.

wt???

**Comment by Artenuvielle** [comment]
Could you please also provide the font file you were trying to use?

**Comment by jiangyi0923** [comment]
[arcdps_font.zip](https://github.com/Artenuvielle/GW2-SCT/files/6215623/arcdps_font.zip)
arcdps and sct all used it ,then well sct can't load this font , and the game well close , if not close the sct well use  default font

**Comment by Artenuvielle** [comment]
Error cannot be reproduced with current build. Without additional feedback I will close this issue in a week.
