### ISSUE TITLE
Crashing with new Guild Wars 2 Build

### ISSUE THREAD

**Issue by anonymous3123** [Artenuvielle/GW2-SCT#31]
arcdps was causing crashing following the Guildwars 2 update on 4/29/2021. Updated arcdps to 4/29 build and no change.

Removed SCT and the crashes stopped.

Crashlog crash section:

```
Apr 29 23:50:04 arcdps 20210429.212955-360-x64
Apr 29 23:50:04 client: gw2 0x7FF73AF90000-0x7FF73D53C000 (0x77F9AE7B)
Apr 29 23:50:04 client: arcdps 0x7FFE22590000-0x7FFE226BA000 (0x06CDD5E3)
Apr 29 23:50:05 extensions: GW2 SCT 0x7FFE21B10000-0x7FFE21C3D000 (2.0a, 0x27B89E50)
Apr 29 23:50:05 config: loading from "F:\Program Files\Guild Wars 2\addons\arcdps\arcdps.ini"
Apr 29 23:50:05 client: ready
Apr 29 23:50:27 error: intercepted crash from hardware exception in "F:\Program Files\Guild Wars 2\bin64\d3d9.dll"
Apr 29 23:50:27 client: --- exception ---
			code: 0x00000000C0000005
			addr: 0x00007FFE225C1319
			offs: 0x0000000000031319
			prms:   0000000000000002
			flgs: 0x0000000000000000
```

**Comment by SaiyanOfDarkness** [comment]
> arcdps was causing crashing following the Guildwars 2 update on 4/29/2021. Updated arcdps to 4/29 build and no change.
> 
> Removed SCT and the crashes stopped.
> 
> Crashlog crash section:
> 
> ```
> Apr 29 23:50:04 arcdps 20210429.212955-360-x64
> Apr 29 23:50:04 client: gw2 0x7FF73AF90000-0x7FF73D53C000 (0x77F9AE7B)
> Apr 29 23:50:04 client: arcdps 0x7FFE22590000-0x7FFE226BA000 (0x06CDD5E3)
> Apr 29 23:50:05 extensions: GW2 SCT 0x7FFE21B10000-0x7FFE21C3D000 (2.0a, 0x27B89E50)
> Apr 29 23:50:05 config: loading from "F:\Program Files\Guild Wars 2\addons\arcdps\arcdps.ini"
> Apr 29 23:50:05 client: ready
> Apr 29 23:50:27 error: intercepted crash from hardware exception in "F:\Program Files\Guild Wars 2\bin64\d3d9.dll"
> Apr 29 23:50:27 client: --- exception ---
> 			code: 0x00000000C0000005
> 			addr: 0x00007FFE225C1319
> 			offs: 0x0000000000031319
> 			prms:   0000000000000002
> 			flgs: 0x0000000000000000
> ```

arcdps had an update recently, did that fix the issue for you?

**Comment by anonymous3123** [comment]
It appears one of his builds did fix this issue, most likely the

` apr.30.2021: fixed a crash in previous.`
