### ISSUE TITLE
Open source timeline

### ISSUE THREAD

**Issue by psykzz** [Artenuvielle/GW2-SCT#36]
You mentioned previously about the plan to make the code open source.
> I plan to make the project open source soon

Any updates or progress to share?

**Comment by Artenuvielle** [comment]
Sure. I recently returned to actively refactoring the whole GW2 SCT core. Once I'm done with that and it seems to run smoothly in personal testing, I will probably create a new release candidate 2.0b together with publishing the code. My guess it that this takes at least another week.

If you are interested in special parts of the source, feel free to ask here or send me a direct message on reddit or discord.
