### ISSUE TITLE
Hello I'm here again

### ISSUE THREAD

**Issue by jiangyi0923** [Artenuvielle/GW2-SCT#4]
In PVP, Raid,Fractal, maps, SCT will have bugs that will cause the game to end,
Is the array too small, overflow, or not the normal destruction of the release?

**Comment by Artenuvielle** [comment]
I just updated ArcDPS for some testing and somehow I get heavy FPS drops now. I think it's very hard to reproduce the crashes you are talking abaout under this conditions.

The shown messages are stored internally in a std::vector and their memory should get released properly once the message flows out of display bounds. You could try to narrow down the source by testing if the issue persists if you turn off skill icons or use default font or if it is maybe tied to one class or one special type of message that causes a crash.
