### ISSUE TITLE
Support for DX 11?

### ISSUE THREAD

**Issue by thanhtong89** [Artenuvielle/GW2-SCT#40]
How would we be able to load the DLL module when opting into the DX11 beta currently? ArcDPS works fine there when renamed to d3d11.dll, but it looks like just renaming the sct's DLL won't work. Thanks!

**Comment by Artenuvielle** [comment]
No need to rename the sct dll. Just keep it as d3d9_arcdps_sct.dll inside your *game_dir/bin64* directory.

**Comment by thanhtong89** [comment]
Hey thanks! I was doing extra work for nothing! xD
