### ISSUE TITLE
Crash when backspacing through template 

### ISSUE THREAD

**Issue by justinttl** [Artenuvielle/GW2-SCT#41]
First off, just want to say thank you for creating such an amazing mod. The options and templating language features are truly 💯!

I have noticed when tweaking in options that whenever I backspace through something like `[col=FFFFFF]%v[/col]` to `[%v[/col]`, the game client will crash. Upon restarting, I lose a lot of my configuration. 

I wonder if this is a bug in the template evaluation logic?

**Comment by Artenuvielle** [comment]
Yeah, that sounds like a bug. I will have a look into it.

**Comment by Artenuvielle** [comment]
Will be fixed with commit https://github.com/Artenuvielle/GW2-SCT/commit/37a3d663e5f5df20e32bddae5462e5de9b750b35
