### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Sushi-Zero** [Artenuvielle/GW2-SCT#42]
Running GW2 with DX11 Beta. I have installed SCT using the addon manager. Nothing happens once installed. The menu information appears but there is not SCT displayed only the default ingame one. I noticed it is also not possible to adjust the SCT text scroll area at all and it defaults to 0.0. 

I turned off DX11 Beta and it worked. I then changed back to DX11 and it caused the game to shut down every time I entered combat. I then had to remove SCT entirely and everything went back to normal sans SCT of course

**Comment by Artenuvielle** [comment]
Dx11 ist currently only supported for the prerelease versions of SCT. I think those are not downloaded by the addon manager. If you want to test SCT with dx11 allread, pleased install a newer version manually.

**Comment by Sushi-Zero** [comment]
Thanks
________________________________
