### ISSUE TITLE
SCT Width & Heigh flicker between 0 and 1

### ISSUE THREAD

**Issue by Gramgoyle** [Artenuvielle/GW2-SCT#49]
Like the title suggest, my GW2 SCT for some reason not show up and when I check the "Scroll Area" option I notice that the Width & Heigh flicker between 0 and 1 constantly.

When I check the sct.ini

it clearly state that the Width = 40.000000 and Height = 260.000000

well it happening after April 19 2022 update, not sure maybe required arcdps update or it come from the dll itself.

**Comment by Artenuvielle** [comment]
Which version of SCT are you using? The most current one uses a file called "sct.json" for storing preferences instead of the old "sct.ini".

**Comment by Gramgoyle** [comment]
Ah! Thank you for pointing it out.

I was using the outdated version 1.3 RC4 - since it was the latest (released) on the main page. Meanwhile the latest build actually the 2.0 RC3 which is kinda hidden because it shown as (pre-released).

Well, I learn something new today about gif hub :3

**Comment by Gramgoyle** [comment]
Ah! Thank you for pointing it out.

I was using the outdated version 1.3 RC4 - since it was the latest (released) on the main page. Meanwhile the latest build actually the 2.0 RC3 which is kinda hidden because it shown as (pre-released).

Well, I learn something new today about gif hub :3
