### ISSUE TITLE
Please boss

### ISSUE THREAD

**Issue by jiangyi0923** [Artenuvielle/GW2-SCT#6]
ArcDPS Mechanics Plugin is Published source code now

https://github.com/MarsEdge/GW2-ArcDPS-Mechanics-Log

so How to solve Chinese Sct Plugin Incompatible with Mechanics Plugin?

Important! The font becomes "?"

**Comment by Artenuvielle** [comment]
Can you provide the source where the mechanic plugin got permission to publish the source code?
Back when my plugin got approved by Chris Cleary, not publishing my code was one of the prerequisites.

**Comment by jiangyi0923** [comment]
No, thanks. I've already solved it
