### ISSUE TITLE
The new version of arcdps need adaptation

### ISSUE THREAD

**Issue by jiangyi0923** [Artenuvielle/GW2-SCT#7]
The new version of arcdps need adaptation , Get damage to show error, damage has been changed to heal, wish to update

**Comment by Stefanovicc** [comment]
I got the same issue, alle damage is shown as +heal. I really like this plugin, hope this can be fixed :)

**Comment by caiofe01** [comment]
if any of you guys have the arc dps version that are working with the actual release, please zip it somewherem i'm having trouble to find arround;

**Comment by jiangyi0923** [comment]
[d3d9.zip](https://github.com/Artenuvielle/GW2-SCT/files/4234700/d3d9.zip)

**Comment by caiofe01** [comment]
o.o sir.. i think the d3d9 in the .zip is the actual one.. if its working with it.. (here is not opening the addon with this d3d9 + the 'd3d9_arcdps_sct.dll' in the bin64 folder;
If it's actually working ( it at least opens ) when u use them in the bin64; could you sent me the 'addon' folder of this addon that should be generated when open the game (i think my d3d9_ardps_sct are not triggering)

**Comment by jiangyi0923** [comment]
[jz2.zip](https://github.com/Artenuvielle/GW2-SCT/files/4236663/jz2.zip)

**Comment by caiofe01** [comment]
so.. sir.. when i paste the archives of this zip, the arc dps appears in chinese ( saw that it is related to a lang archive ) but the 'sct' option in the arc dps menu does not appear.. i really don't know why since in theory these folders should be working just pasting in the gw2 main folder, right?

**Comment by Artenuvielle** [comment]
This was resolved with version 1.2RC-1
