### ISSUE TITLE
Skill Icons

### ISSUE THREAD

**Issue by livarkhal** [Artenuvielle/GW2-SCT#9]
Hi,

Ty for your patch, this work fine :) 

I have a question about skills icons ... There is not all skill icons (for exemple, "Sword of Justice" on the guard), is it normal?

And i wan't to help you to add translate in french, how can i help you for this? :)

**Comment by Artenuvielle** [comment]
for the translation just look at the lang.ini file located at "GW2 install dir\addons\sct\lang.ini" and edit it with any editor. Afterwards feel free to reply this file here, so that I can publish it for other people aswell.

For the skill icons:
For the given skill I checked the skill id I get from the arcdps api, which is 46469 for Sword of Justice. However the GW2 API does not know this skill id https://api.guildwars2.com/v2/skills?ids=46469.
Instead it knows the skill by id 9168 (https://api.guildwars2.com/v2/skills?ids=9168). Not sure what's happening there. I'll investigate.

**Comment by livarkhal** [comment]
Ok, thanks :) i trnaslate the file and i send it to you fast ;)

**Comment by livarkhal** [comment]
This is the french version, just delete the .txt

[lang.ini.txt](https://github.com/Artenuvielle/GW2-SCT/files/4388913/lang.ini.txt)

**Comment by Artenuvielle** [comment]
At most of the places the windows should scale automatically. If you encounter issues somewhere, feel free to post it here.

Concerning the skill icons missing for sword of justice, this is what deltaconnected told me:
in the case of soj the skill on your bar summons the spinny sword and the spinny sword casts the spin that you see doing damage. how each skill is implemented idk

This may not be the only skill. I will maybe implement a skill id mapping list in future releases.

**Comment by livarkhal** [comment]
ok, i 2 problems of windows size :
-In the General, we don't see all the line at "Nombre maximal de message dans la file"
-In "Message", "Incomming Player", at the place of "Avalaible template model" (Paramètres de modèle utilisable), the window is flashing ...

i don't understand for the icons :/ my english is not very good as you can see xD
But yeah Sword of Justice was just a example, the icons for the condi don't work too, and other skills ...

**Comment by Artenuvielle** [comment]
The first sizing problem is difficult to solve. You can enlarge your SCT options window though by dragging the lower right corner.
The second sizing problem was actually a bug I found and it will be fixed in version 1.2-RC2.

Condi icons should work though. Which skill did you use and have you made sure that you actually enabled icons in the according options tab?

**Comment by livarkhal** [comment]
The burn icon don't work ... i used it with the F1 of the guard, and sword of justice. The icons are enabled :)

**Comment by Artenuvielle** [comment]
Could you double check that inside the 'gw2 install/addons/sct/icons/' there is a 737.jpg that looks like the burning icon.
If yes, please go to ardps option and enable the 'Log' window. Rightclick it and select 'Channel' > 'combat - local'. Then use F1 and sword of justice on an enemy. After you see the log output it would be nice if you could provide a screenshot of that logging window.

**Comment by livarkhal** [comment]
I don't have 737.jpg ...

**Comment by livarkhal** [comment]
I don't have 737.jpg ...

**Comment by Artenuvielle** [comment]
Very odd. Maybe just put it there manually?
![737](https://user-images.githubusercontent.com/2743399/77924357-e24aa580-72a3-11ea-9a7c-9fdbd07cc339.jpg)

**Comment by livarkhal** [comment]
It's ok, when i add it manually it works fine.
But i have to add manually all the icons lost?

**Comment by Artenuvielle** [comment]
There shouldn't be too many. I'll compile some zip archives of them and provide them on the git repo soon.

**Comment by Artenuvielle** [comment]
I added an option to remap skill id's in the newest version of SCT (1.3 onwards). You can check the arcdps log ingame and see which skill id triggers an event where no skill icon is shown in SCT. Then look the id of the skill up that should be displayed and remap in a remap.ini file the wrong to thew correct id's. Here is an example file (you gotta place it in SCT directory and rename the file extenstion to .ini):

[remap.txt](https://github.com/Artenuvielle/GW2-SCT/files/4419339/remap.txt)

**Comment by livarkhal** [comment]
ok, i will try it, but i can't access SCT options since the last update :o in the arcdps options i don't have sct ...

**Comment by Artenuvielle** [comment]
can you check in arcdps.ini if it is loaded at all? Also make sure it is in the right location and named correctly?

**Comment by livarkhal** [comment]
[arcdps.txt](https://github.com/Artenuvielle/GW2-SCT/files/4438393/arcdps.txt)
Here is my arcdps.ini .

**Comment by Artenuvielle** [comment]
Sorry, I meant arcdps.log

**Comment by livarkhal** [comment]
[arcdps.log](https://github.com/Artenuvielle/GW2-SCT/files/4438785/arcdps.log)
:)

**Comment by Artenuvielle** [comment]
Okay SCT gets not even loaded. You seem to have another d3d9.dll which gets chainloaded. Can you elaborate which addon dll's you installed where on your gw2 install?

**Comment by livarkhal** [comment]
I use GW2 Radial :)

**Comment by Artenuvielle** [comment]
I tested the compatibility with this addon at least when using the unofficial addon manager.

**Comment by livarkhal** [comment]
You tested it and it works for you?
